version: "3.9"

services:
  mongo_assignment:
    image: mongo:6
    container_name: mongo_assignment
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Ahmed
      MONGO_INITDB_ROOT_PASSWORD: "ahmed123"
      MONGO_INITDB_DATABASE: AhmedDB
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
